### ISSUE TITLE
Help to add solutions.

### ISSUE THREAD

**Issue by meta-priyansh-bhardwaj** [meta-priyansh-bhardwaj/problem-solving#1]

**Comment by kashc11** [comment]
Hi! Can I contribute to this?

**Comment by meta-priyansh-bhardwaj** [comment]
@kashc11 Sure you can.

**Comment by psymbio** [comment]
Hey, can you assign this issue to me? I have leetcode solution.

**Comment by meta-priyansh-bhardwaj** [comment]
@psymbio go on make your contribution.

**Comment by psymbio** [comment]
yep, done

**Comment by shubhamnag14** [comment]
can you assign this issue to me??i would like to contribute

**Comment by meta-priyansh-bhardwaj** [comment]
@shubhamnag14  Sure, go on make your contribution.

**Comment by MariamFahmy98** [comment]
I have added a new problem solution from codeforces about graphs in c++, could you please review the pull requests?
thanks in advance

**Comment by meta-priyansh-bhardwaj** [comment]
@MariamFahmy98 PR is merged now, thanks for you contribution.
